### ISSUE TITLE
When used in a module: duplicate definition of symbol in

### ISSUE THREAD

**Issue by kuerbis** [ab5tract/Terminal-Print#40] opened 2017-07-12 07:18 UTC
When I use Terminal::Print in a module I get this error: "P6M Merging GLOBAL symbols failed: duplicate definition of symbol in"

The code used:

    use v6;
    unit class my_module;
    use Terminal::Print;

and

    #!/usr/bin/env perl6
    use v6;
    use lib '.';
    use my_module;

**Comment by Xliff** [comment] 2017-08-22 15:49
This looks to have been caused by rakudo. I am running

```
This is Rakudo version 2017.08-4-g636a3c126 built on MoarVM version 2017.08.1
implementing Perl 6.c.
```

And I do not get this error.

**Comment by kuerbis** [comment] 2017-08-29 05:56
I updated rakudo but get still the error message.

`This is Rakudo version 2017.08-5-g593fa5f87 built on MoarVM version 2017.08.1-19-g151a2563
implementing Perl 6.c. `

**Comment by ab5tract** [comment] 2017-08-29 13:26
Hi @kuerbis , can you try the branch `no-more-auto-create` and see if this resolves the issue?

**Comment by kuerbis** [comment] 2017-08-29 16:25
Didn't find it. Can you post a link?

**Comment by ab5tract** [comment] 2017-08-29 16:45
https://github.com/ab5tract/Terminal-Print/tree/no-more-auto-create

**Comment by kuerbis** [comment] 2017-08-31 10:17
With this branch it works (no error messages).

**Comment by ab5tract** [comment] 2017-09-01 08:33
Thanks for checking! The branch has been merged. Please let us know if you have any further issues.

**Closed by ab5tract** 2017-09-01 08:33 UTC
